# Generated by Django 5.1.1 on 2024-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_cover',
            field=models.FileField(upload_to='track_covers'),
        ),
    ]
