# Generated by Django 5.1.1 on 2024-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_track_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_cover',
            field=models.ImageField(upload_to='track_covers'),
        ),
    ]
